name: Release

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Deploy artifact with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.m2
          echo "<?xml version='1.0' encoding='UTF-8' ?> <settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd' xmlns='http://maven.apache.org/SETTINGS/1.0.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'> <servers> <server> <id>bintray-uio-bmi-TSD-File-API-client</id> <username>${{secrets.MAVEN_USER}}</username> <password>${{ secrets.MAVEN_TOKEN }}</password> </server> </servers> </settings>" > ~/.m2/settings.xml
          mvn javadoc:javadoc
          mvn deploy
