name: Release

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: create maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id":"github-tsd-file-api-client",
              "username": "${{github.actor}}",
              "password": "${{ secrets.MAVEN_TOKEN }}"
            }]
      - name: deploy maven
        run: mvn deploy
